version: '3'
services:
  flask:
    container_name: flask
#    image: shomaigu/flask-base:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    tty: true
    volumes:
    - ./flask/requirements.txt /usr/src/app/
    - ./flask/app.py /usr/src/app/app.py
    - ./flask/templates/head.html /usr/src/app/templates/head.html
    - ./flask/static /usr/src/app/static
